services:
  redis:
    image: redis:7-alpine
    container_name: chai-aur-redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    
  mongodb:
    image: mongo:7
    container_name: chai-aur-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: chai_aur_mongo
    volumes:
      - mongo-data:/data/db
      
volumes:
  redis-data:
  mongo-data: